services:
  postgres:
    container_name: boogoo_postgres
    image: postgres:15
    restart: always
    networks:
      - back-tier
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: boogoo_redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - back-tier
    volumes:
      - ./.redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env

  nginx:
    container_name: boogoo_nginx
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    networks:
      - back-tier
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  app:
    container_name: boogoo_app
    image: ${IMAGE_TAG}
    networks:
      - back-tier
    env_file:
      - .env

networks:
  back-tier: {}
