services:
  postgres:
    container_name: boogoo_postgres
    image: postgres:15
    restart: always
    networks:
      - back-tier
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: boogoo_redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - back-tier
    volumes:
      - ./.redis_data:/data
    env_file:
      - .env

  app:
    container_name: boogoo_app
    image: ${IMAGE_TAG}
    networks:
      - back-tier
    env_file:
      - .env

networks:
  back-tier: {}
