services:
  postgres:
    env_file:
      - .env.local
  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    env_file:
      - .env.local
