name: CI/CD Pipeline

env: 
  IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/boogooman:${{ github.sha}}

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Log in to Docker Hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        echo "Step 2 completed - logged to DockerHub"

    - name: Build and Push image 
      run: | 
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "Step 3 completed - built a new image"
        docker push $IMAGE_TAG 
        echo "Step 4 completed - pushed to DockerHub"
        echo "BOOGOOMAN_IMAGE_TAG=$IMAGE_TAG" > .env
        head .env

    - name: SSH into EC2 and remove old docker-compose.yml
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_URL}}
        username: ${{ secrets.VPS_USER}}  
        key: ${{ secrets.VPS_SSH}}  
        script: |
          cd /home/ubuntu/app/
          echo "${{env.IMAGE_TAG}} >> .env 