name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkoutc ode
      uses: actions/checkout@v2
    - name: Print message after Checkout
      run: echo "Step 1 completed  - Checked out code"
  
    - name: Log in to Docker Hub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Print messge after DockerHub login
      run: echo "Step 2 completed - Logged into DockerHub" 