name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print message after Checkout
      run: echo "Step 1 completed  - Checked out code"
  
    - name: Log in to Docker Hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        echo "Step 2 completed - logged to DockerHub"
    - name: Build and Post image 
      run: | 
        docker build . --file Dockerfile --tag boogooman:${{ github.sha }}
        echo "Step 3 completed - built a new image"
        docker push boogooman:${{ github.sha }}
        echo "Step 4 completed - pushed to DockerHub"